### ISSUE TITLE
Bug with round

### ISSUE THREAD

**Issue by krzakala** [amanoel/juliamp#1]
Which version of Julia are you using? If I try
include("test.jl")
ERROR: `round` has no method matching round(::Type{Int64}, ::Float64)
 in include at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/florent/GitHub/juliamp/test.jl, in expression starting on line 13

Essentially, it is because of the round in line 13
k, m = round(Int, ceil(rho * n)), round(Int, ceil(alpha * n))

**Comment by krzakala** [comment]
I replace these lines by int(ceil(rho * n)) but now I cannot use the dot together with array view :-( Wondering what is going on...

**Comment by amanoel** [comment]
I'm using 0.4, and indeed I've added this line when moving from 0.3 to 0.4 since it was complaining about it! I get the following warning in v0.4 if I use int(ceil(rho * n)):

WARNING: int(x::AbstractFloat) is deprecated, use round(Int,x) instead.
 in int at ./deprecated.jl:49

What error are you getting now? I'm gonna run the code on v0.3 to see what I get, just a moment.

**Comment by krzakala** [comment]
include("test.jl")
ERROR: `dot` has no method matching dot(::Int64, ::ContiguousView{Float64,1,Array{Float64,2}}, ::Int64, ::Array{Float64,1}, ::Int64)
 in iterate_swamp at /Users/florent/GitHub/juliamp/JuliAMP.jl/src/swamp.jl:41

**Comment by krzakala** [comment]
At the same time, I used the old 0.3.10 ... Maybe I should move to 0.4 but I though I should wait the release in few weeks?

**Comment by krzakala** [comment]
I guess I should probably move to 0.4 ?

**Comment by alaa-saade** [comment]
Maybe the compat package can help
Le mer. 26 août 2015 à 20:52, Florent Krzakala <notifications@github.com> a
écrit :

**Comment by krzakala** [comment]
Yes it looks like, but I am not sure how much we should worry about this if it works with Julia 0.4 which will be the official realease in few weeks! Alaa, how should I install 0.4 on mac?

**Comment by amanoel** [comment]
Well, in my experience 0.4 is pretty much stable by now (even though it's still in development), and runs faster than 0.3... So it should be okay I guess.
But it's weird that it doesn't work on 0.3, apparently the BLAS wrapper for the dot function is not compatible w/ ArrayViews in 0.3.

I didn't know about the Compat package, it could help indeed!

**Comment by krzakala** [comment]
OK, I moved to 0.4 and minus a problem with Winston (which i fixed with Pkg.checkout("Winston") it works fine now. Let's close this issue

**Comment by krzakala** [comment]
close
